### ISSUE TITLE
[Feature request] Time chart

### ISSUE THREAD

**Issue by Hubbit200** [saraqael-m/WaniKaniMiscStats#7]
Might a chart to show the amount of time per day spent doing reviews/lessons be possible? I'd love to be able to get an idea of how long I'm spending on WaniKani each day!

**Comment by saraqael-m** [comment]
Am on it! It's already on the to-do list.

**Comment by saraqael-m** [comment]
Progress Update:
![image](https://user-images.githubusercontent.com/80643194/175666271-ab3d688c-85b1-4256-9edb-7168461dafde.png)

Here is a preview. You can see that the time one took for reviews each day is shown. Is this what you had in mind?
Next I will add a moving average options like for the other charts and a "total review time" chart.

**Comment by Hubbit200** [comment]
It looks great!
The "total" line is a bit hard to see, so maybe it would be better pure white like on the other charts? At least in my opinion it's usually going to be the most useful one so it would be nice if it were easier to distinguish from the others. Also maybe the tooltip "Radical" should be the plural "Radicals"?

The 2 minute method seems like a great idea! If it's easy it could maybe be nice to make it a customizable setting though?

But overall it's looking great :)

**Comment by saraqael-m** [comment]
![image](https://user-images.githubusercontent.com/80643194/178592632-73365608-b9f5-475b-8b68-c140f98c81b9.png)

The total is pure white in dark mode. Fixed the "radicals" typo, too! The time frame is a customizable setting. There is a "total time" chart now as well! With that I'll close this request :)
